language: r
dist: trusty
latex: false
pandoc_version: 2.3.1
sudo: false

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin


script:
  - Rscript -e 'install.packages("remotes")'
  - Rscript -e 'remotes::install_github("rstudio/blogdown")'
#  - Rscript -e 'blogdown::install_hugo(version = "v0.52")'
  - Rscript check_rmd_pkg.R; cat need_install.txt
  - Rscript -e 'blogdown::build_site(run_hugo = FALSE)'

after_success:
  - ls -d content/* | xargs -n 1 basename > public/invalid_names.txt
  - mv need_install.txt public/

deploy:
  provider: pages
  target-branch: web
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  on:
    branch: master
#  local_dir: public
